// Auto-selected images per day from public/images/Day1~Day7 folders
// Each path is relative to Next.js public folder (starts with "/images/")

export const imagesByDay: Record<string, string[]> = {
  // Optional: Day 0 (e.g., Departure) — used only in itinerary, not in Gallery
  // Add image paths under public/ as needed, e.g., "/images/itinerary/d0/1.jpg"
  d1: [
    "/images/itinerary/d1/1.jpeg",
    "/images/itinerary/d1/2.png",
    "/images/itinerary/d1/3.png",
    "/images/itinerary/d1/4.png",
  ],
  d2: [
    "/images/itinerary/d3/1.jpeg",
    "/images/itinerary/d3/2.jpg",
    "/images/itinerary/d3/3.jpg",
    "/images/itinerary/d3/4.jpg",
    "/images/itinerary/d3/5.png",
    "/images/itinerary/d3/6.jpg",
    "/images/itinerary/d3/7.jpg",
    "/images/itinerary/d3/8.jpg",
    "/images/itinerary/d3/9.jpg",
    "/images/itinerary/d3/10.jpg",
    "/images/itinerary/d3/11.jpg",
    "/images/itinerary/d3/12.jpg",
    "/images/itinerary/d3/13.jpg",
    "/images/itinerary/d3/14.jpg",
    "/images/itinerary/d3/15.jpg",
    "/images/itinerary/d3/16.jpg",
    "/images/itinerary/d3/17.jpg",
  ],
  d3: [
    "/images/itinerary/d4/1.jpg",
    "/images/itinerary/d4/2.jpg",
    "/images/itinerary/d4/3.jpg",
    "/images/itinerary/d4/4.jpg",
    "/images/itinerary/d4/5.jpg",
    "/images/itinerary/d4/6.jpg",
    "/images/itinerary/d4/7.jpg",
    "/images/itinerary/d4/8.jpg",
    "/images/itinerary/d4/9.jpg",
    "/images/itinerary/d4/10.jpg",
    "/images/itinerary/d4/11.jpg",
    "/images/itinerary/d4/12.jpg",
    "/images/itinerary/d4/13.jpg",
  ],
  d4: [
    "/images/itinerary/d5/1.jpg",
    "/images/itinerary/d5/2.webp",
    "/images/itinerary/d5/3.webp",
    "/images/itinerary/d5/4.jpg",
    "/images/itinerary/d5/5.png",
    "/images/itinerary/d5/6.jpg",
    "/images/itinerary/d5/7.jpg",
    "/images/itinerary/d5/8.jpg",
    "/images/itinerary/d5/9.jpg",
    "/images/itinerary/d5/10.jpg",
    "/images/itinerary/d5/11.jpg",
    "/images/itinerary/d5/12.jpg",
    "/images/itinerary/d5/13.webp",
    "/images/itinerary/d5/14.jpg",
    "/images/itinerary/d5/15.jpg",
  ],
  d5: [
    "/images/itinerary/d6/1.jpg",
    "/images/itinerary/d6/2.jpeg",
    "/images/itinerary/d6/3.jpg",
    "/images/itinerary/d6/4.jpg",
    "/images/itinerary/d6/5.png",
    "/images/itinerary/d6/6.jpg",
    "/images/itinerary/d6/7.jpg",
    "/images/itinerary/d6/8.jpg",
  ],
  d6: [
    "/images/itinerary/d7/1.png",
    "/images/itinerary/d7/2.webp",
    "/images/itinerary/d7/3.jpg",
    "/images/itinerary/d7/4.jpg",
    "/images/itinerary/d7/5.jpg",
    "/images/itinerary/d7/6.jpg",
    "/images/itinerary/d7/7.jpg",
    "/images/itinerary/d7/8.jpg",
    "/images/itinerary/d7/9.jpg",
    "/images/itinerary/d7/10.jpg",
    "/images/itinerary/d7/11.jpg",
    "/images/itinerary/d7/12.jpg",
    "/images/itinerary/d7/13.jpg",
  ],
  d7: [
    "/images/itinerary/d8/1.jpg",
    "/images/itinerary/d8/2.jpg",
    "/images/itinerary/d8/3.jpg",
    "/images/itinerary/d8/4.jpg",
    "/images/itinerary/d8/5.jpg",
    "/images/itinerary/d8/6.jpg",
    "/images/itinerary/d8/7.jpg",
    "/images/itinerary/d8/8.jpg",
    "/images/itinerary/d8/9.jpg",
    "/images/itinerary/d8/10.jpg",
    "/images/itinerary/d8/11.jpg",
    "/images/itinerary/d8/12.jpg",
    "/images/itinerary/d8/13.jpg",
    "/images/itinerary/d8/14.jpg",
    "/images/itinerary/d8/15.jpg",
  ],
  d8: [
    "/images/itinerary/d9/1.jpeg",
    "/images/itinerary/d9/2.jpg",
    "/images/itinerary/d9/3.jpg",
    "/images/itinerary/d9/4.jpg",
    "/images/itinerary/d9/5.jpg",
    "/images/itinerary/d9/6.jpg",
    "/images/itinerary/d9/7.jpg",
    "/images/itinerary/d9/8.jpg",
    "/images/itinerary/d9/9.jpg",
    "/images/itinerary/d9/10.jpg",
    "/images/itinerary/d9/11.jpg",
  ],
  d9: [
    "/images/itinerary/d10/1.jpg",
    "/images/itinerary/d10/2.jpg",
    "/images/itinerary/d10/3.jpg",
    "/images/itinerary/d10/4.jpg",
    "/images/itinerary/d10/5.jpg",
    "/images/itinerary/d10/6.jpg",
    "/images/itinerary/d10/7.jpg",
    "/images/itinerary/d10/8.jpg",
    "/images/itinerary/d10/9.jpg",
    "/images/itinerary/d10/10.jpg",
    "/images/itinerary/d10/11.jpg",
    "/images/itinerary/d10/12.jpg",
    "/images/itinerary/d10/13.jpg",
    "/images/itinerary/d10/14.jpg",
    "/images/itinerary/d10/15.jpg",
    "/images/itinerary/d10/16.jpg",
    "/images/itinerary/d10/17.jpg",
    "/images/itinerary/d10/18.jpg",
    "/images/itinerary/d10/19.jpg",
  ],
  d10: [
    "/images/itinerary/d11/1.jpg",
    "/images/itinerary/d11/2.jpg",
    "/images/itinerary/d11/3.jpg",
    "/images/itinerary/d11/4.jpg",
    "/images/itinerary/d11/5.jpg",
    "/images/itinerary/d11/6.jpg",
    "/images/itinerary/d11/7.jpg",
    "/images/itinerary/d11/8.jpg",
    "/images/itinerary/d11/9.webp",
    "/images/itinerary/d11/10.png",
  ],
};
