// Auto-selected images per day from public/images/Day1~Day7 folders
// Each path is relative to Next.js public folder (starts with "/images/")

export const imagesByDay: Record<string, string[]> = {
  // Optional: Day 0 (e.g., Departure) — used only in itinerary, not in Gallery
  // Add image paths under public/ as needed, e.g., "/images/itinerary/d0/1.jpg"
  d1: [
    "/images/itinerary/d1/1.jpeg",
    "/images/itinerary/d1/2.png",
    "/images/itinerary/d1/3.png",
    "/images/itinerary/d1/4.png",
  ],
  d2: [
    "/images/itinerary/d2/1.png",
    "/images/itinerary/d2/2.png",
    "/images/itinerary/d2/3.png",
    "/images/itinerary/d2/4.png",
  ],
  d3: [
    "/images/itinerary/d3/1.png",
    "/images/itinerary/d3/2.png",
    "/images/itinerary/d3/3.png",
    "/images/itinerary/d3/4.png",
    "/images/itinerary/d3/5.jpg",
    "/images/itinerary/d3/6.jpg",
    "/images/itinerary/d3/7.jpg",
    "/images/itinerary/d3/8.png",
  ],
  d4: [
    "/images/itinerary/d4/1.jpg",
    "/images/itinerary/d4/2.jpg",
    "/images/itinerary/d4/3.png",
    "/images/itinerary/d4/4.png",
    "/images/itinerary/d4/5.webp",
    "/images/itinerary/d4/6.jpg",
    "/images/itinerary/d4/7.png",
    "/images/itinerary/d4/8.png",
    "/images/itinerary/d4/9.png",
    "/images/itinerary/d4/10.jpg",
    "/images/itinerary/d4/11.jpg",
    "/images/itinerary/d4/12.jpg",
    "/images/itinerary/d4/13.jpg",
  ],
  d5: [
    "/images/itinerary/d5/1.jpg",
    "/images/itinerary/d5/2.jpg",
    "/images/itinerary/d5/3.jpg",
    "/images/itinerary/d5/4.jpg",
  ],
  d6: [
    "/images/itinerary/d6/1.jpeg",
    "/images/itinerary/d6/2.jpg",
    "/images/itinerary/d6/3.jpg",
    "/images/itinerary/d6/4.jpg",
    "/images/itinerary/d6/5.jpg",
    "/images/itinerary/d6/6.jpg",
    "/images/itinerary/d6/7.jpg",
    "/images/itinerary/d6/8.png",
    "/images/itinerary/d6/9.png",
  ],
  d7: [
    "/images/itinerary/d7/1.png",
    "/images/itinerary/d7/2.webp",
    "/images/itinerary/d7/3.jpg",
    "/images/itinerary/d7/4.jpg",
    "/images/itinerary/d7/5.jpg",
    "/images/itinerary/d7/6.png",
    "/images/itinerary/d7/7.png",
    "/images/itinerary/d7/8.png",
    "/images/itinerary/d7/9.png",
  ],
  d8: [
    "/images/itinerary/d8/1.jpg",
    "/images/itinerary/d8/2.jpg",
    "/images/itinerary/d8/3.webp",
    "/images/itinerary/d8/4.webp",
    "/images/itinerary/d8/5.jpg",
    "/images/itinerary/d8/6.png",
    "/images/itinerary/d8/7.jpg",
    "/images/itinerary/d8/8.jpg",
  ],
  d9: [
    "/images/itinerary/d9/1.jpg",
    "/images/itinerary/d9/2.jpg",
    "/images/itinerary/d9/3.png",
    "/images/itinerary/d9/4.png",
    "/images/itinerary/d9/5.png",
    "/images/itinerary/d9/6.png",
    "/images/itinerary/d9/7.png",
  ],
  d10: [
    "/images/itinerary/d10/1.png",
    "/images/itinerary/d10/2.png",
    "/images/itinerary/d10/3.png",
    "/images/itinerary/d10/4.jpg",
    "/images/itinerary/d10/5.jpg",
    "/images/itinerary/d10/6.jpg",
    "/images/itinerary/d10/7.jpg",
    "/images/itinerary/d10/8.png",
    "/images/itinerary/d10/9.png",
    "/images/itinerary/d10/10.png",
  ],
};
