// Auto-selected images per day from public/images/Day1~Day7 folders
// Each path is relative to Next.js public folder (starts with "/images/")

export const imagesByDay: Record<string, string[]> = {
  // Optional: Day 0 (e.g., Departure) — used only in itinerary, not in Gallery
  // Add image paths under public/ as needed, e.g., "/images/itinerary/d0/1.jpg"
  d1: [
    "/images/itinerary/d1/1.jpeg",
    "/images/itinerary/d1/2.png",
  ],
  d2: [
    "/images/itinerary/d2/1.png",
    "/images/itinerary/d2/2.png",
  ],
  d3: [
    "/images/itinerary/d3/1.jpg",
    "/images/itinerary/d3/1.1.jpg",
    "/images/itinerary/d3/1.2.jpg",
    "/images/itinerary/d3/1.3.webp",
    "/images/itinerary/d3/2.jpg",
    "/images/itinerary/d3/3.jpg",
    "/images/itinerary/d3/3.1.jpg",
    "/images/itinerary/d3/3.2.jpg",
    "/images/itinerary/d3/3.3.jpg",
    "/images/itinerary/d3/3.4.jpg",
    "/images/itinerary/d3/3.5.jpg",
    "/images/itinerary/d3/4.jpg",
    "/images/itinerary/d3/5.jpg",
    "/images/itinerary/d3/6.jpg",
    "/images/itinerary/d3/7.jpg",
    "/images/itinerary/d3/8.jpg",
    "/images/itinerary/d3/9.jpg",
    "/images/itinerary/d3/10.jpg",
    "/images/itinerary/d3/11.jpg",
  ],
  d4: [
    "/images/itinerary/d4/1.jpg",
    "/images/itinerary/d4/2.jpg",
    "/images/itinerary/d4/3.jpg",
    "/images/itinerary/d4/4.jpg",
    "/images/itinerary/d4/5.jpg",
    "/images/itinerary/d4/6.jpg",
    "/images/itinerary/d4/7.jpg",
    "/images/itinerary/d4/8.jpg",
  ],
  d5: [
    "/images/itinerary/d5/1.png",
    "/images/itinerary/d5/1.1.jpg",
    "/images/itinerary/d5/1.2.jpg",
    "/images/itinerary/d5/1.3.jpg",
    "/images/itinerary/d5/2.jpg",
    "/images/itinerary/d5/3.jpg",
    "/images/itinerary/d5/4.webp",
    "/images/itinerary/d5/5.jpg",
    "/images/itinerary/d5/6.jpg",
    "/images/itinerary/d5/7.jpg",
    "/images/itinerary/d5/8.jpg",
    "/images/itinerary/d5/9.jpg",
    "/images/itinerary/d5/10.webp",
    "/images/itinerary/d5/11.jpg",
  ],
  d6: [
    "/images/itinerary/d6/1.jpg",
    "/images/itinerary/d6/2.jpg",
    "/images/itinerary/d6/3.jpg",
    "/images/itinerary/d6/4.1.jpg",
    "/images/itinerary/d6/4.2.jpg",
    "/images/itinerary/d6/4.3.jpg",
    "/images/itinerary/d6/4.jpg",
    "/images/itinerary/d6/5.jpg",
    "/images/itinerary/d6/6.jpg",
  ],
  d7: [
    "/images/itinerary/d7/1.jpg",
    "/images/itinerary/d7/1.1.jpg",
    "/images/itinerary/d7/1.2.jpeg",
    "/images/itinerary/d7/2.jpg",
    "/images/itinerary/d7/3.jpg",
    "/images/itinerary/d7/4.jpg",
    "/images/itinerary/d7/5.1.jpg",
    "/images/itinerary/d7/5.2.jpg",
    "/images/itinerary/d7/5.3.jpg",
    "/images/itinerary/d7/5.4.jpg",
    "/images/itinerary/d7/5.5.jpg",
    "/images/itinerary/d7/5.jpg",
    "/images/itinerary/d7/6.jpg",
  ],
  d8: [
    "/images/itinerary/d8/1.jpg",
    "/images/itinerary/d8/2.jpg",
    "/images/itinerary/d8/3.jpg",
    "/images/itinerary/d8/4.jpg",
    "/images/itinerary/d8/7.jpg",
    "/images/itinerary/d8/8.jpg",
    "/images/itinerary/d8/9.jpg",
    "/images/itinerary/d8/10.jpg",
    "/images/itinerary/d8/11.jpg",
  ],
  d9: [
    "/images/itinerary/d9/1.jpg",
    "/images/itinerary/d9/2.jpg",
    "/images/itinerary/d9/3.1.jpg",
    "/images/itinerary/d9/3.2.jpg",
    "/images/itinerary/d9/3.3.jpg",
    "/images/itinerary/d9/3.jpg",
    "/images/itinerary/d9/4.jpg",
    "/images/itinerary/d9/5.jpg",
    "/images/itinerary/d9/6.webp",
    "/images/itinerary/d9/7.png",
  ],
};
