import fs from 'node:fs';
import path from 'node:path';

const DOC_DIR = path.resolve('Doc');
const GENERATED_DIR = path.resolve('generated');
const OUTPUT_FILE = path.join(GENERATED_DIR, 'html-content.ts');

const filesToRead = {
  agreement_en: '2026-SHS-Agreement-Release-Updated.html',
  agreement_zh_tw: '2026-SHS-Agreement-Traditional-Chinese.html',
  agreement_zh_cn: '2026-SHS-Agreement-Simplified-Chinese.html',
  notes_en: '2026-SHS-Note-Remarks-Updated.html',
  notes_zh_tw: '2026-SHS-Notes-Traditional-Chinese.html',
  notes_zh_cn: '2026-SHS-Notes-Simplified-Chinese.html',
};

let outputContent = `// This file is auto-generated by scripts/generate-html-content.ts\n// Do not edit this file directly.\n\n`;

for (const [key, filename] of Object.entries(filesToRead)) {
  const filePath = path.join(DOC_DIR, filename);
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    // Escape backticks, backslashes, and dollar signs for use in a template literal
    const escapedContent = content.replace(/\\/g, '\\').replace(/`/g, '\`').replace(/\${/g, '\\${');
    // Use simple string concatenation to avoid nesting issues
    outputContent += 'export const ' + key + ' = `' + escapedContent + '`;\n\n';
  } else {
    console.warn(`Warning: HTML file not found, exporting empty string for ${key}: ${filename}`);
    outputContent += `export const ${key} = 
;

`;
  }
}

if (!fs.existsSync(GENERATED_DIR)) {
  fs.mkdirSync(GENERATED_DIR, { recursive: true });
}

fs.writeFileSync(OUTPUT_FILE, outputContent, 'utf8');

console.log(`Successfully generated HTML content at ${OUTPUT_FILE}`);
